### ISSUE TITLE
Should use CFE_FS_InitHeader instead of manually populating

### ISSUE THREAD

**Issue by iamthad** [nasa/DS#1]
DS initializes and populates the CFE FS header itself (see [ds_file.c, lines 273-278](https://github.com/nasa/DS/blob/master/fsw/src/ds_file.c#L273-L278))

This requires DS to understand the details of the header structure and could break if that structure changes.

It should instead use the `CFE_FS_InitHeader` function which is designed to do exactly this.

**Comment by skliper** [comment]
Duplicate of #8
