### ISSUE TITLE
Convert command success events to INFORMATION type

### ISSUE THREAD

**Issue by skliper** [nasa/DS#107]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [README file](https://github.com/nasa/DS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
Command success events in DS are `CFE_EVS_EventType_DEBUG`, example:
https://github.com/nasa/DS/blob/64181647ab455653fbc04b20a43406764862673b/fsw/inc/ds_events.h#L284-L287
https://github.com/nasa/DS/blob/64181647ab455653fbc04b20a43406764862673b/fsw/src/ds_cmds.c#L106

cFE pattern (AFAIK) is event success creates `CFE_EVS_EventType_INFORMATION`.

**Describe the solution you'd like**
Since these are triggered by command only, flooding isn't anticipated and it's useful to see the event nominally.  Would then match nominal pattern in cFE.

**Describe alternatives you've considered**
Change all command success responses to DEBUG, or even add a new command success type.  Consistency is key.

**Additional context**
In concert w/ reporting time stamps in event messages, this makes it easier to quickly verify RTS timing/behavior.  Even without it in the log, the time tagged event messages provide a similar benefit.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
Yes - they should be `INFO`, not `DEBUG`. It is indeed the nominal pattern across cFE/cFS although there are a couple of other apps/components which don't comply fully.

That would align with the cFE Developer's Guide [s7.2](https://github.com/nasa/cFE/blob/main/docs/cFE%20Application%20Developers%20Guide.md#72-event-types). Also, see the reasoning provided [here](https://github.com/nasa/cFE/issues/1712) which makes a lot of sense.
