### ISSUE TITLE
Non-distinct identifiers static analysis warning

### ISSUE THREAD

**Issue by skliper** [nasa/DS#115]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
DS_CloseFileCmd conflict here:
https://github.com/nasa/DS/blob/2a6c6a2df5b2f00915a06f0a5ac30b9c327c725d/fsw/src/ds_cmds.c#L963-L965

**To Reproduce**
Static analysis

**Expected behavior**
Unique identifiers.  TBH calling this variable a Cmd is misleading, it's a pointer to the payload.  Suggest changing to PayloadPtr for all of these command processing routines (which would resolve this issue as well).

**System observed on:**
CodeSonar static analysis

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
2 more instances in the same file that differ only in case (capitalization):
https://github.com/nasa/DS/blob/2a6c6a2df5b2f00915a06f0a5ac30b9c327c725d/fsw/src/ds_cmds.c#L1116-L1118
https://github.com/nasa/DS/blob/2a6c6a2df5b2f00915a06f0a5ac30b9c327c725d/fsw/src/ds_cmds.c#L1214-L1216

`PayloadPtr`, `CommandPtr` or `CmdPtr` seem like the clearest options.

`PayloadPtr` is currently only used for the HK payload in other apps, whereas `CmdPtr` seems to be preferred for the other command payload types.
