### ISSUE TITLE
DS_AddRemoveMid_Payload_t erroneously contains a CommandHeader

### ISSUE THREAD

**Issue by dmknutsen** [nasa/DS#116]
**Checklist (Please check before submitting)**

* [x ] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x ] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
There appears to be a copy and paste error in ds_msg.h.  DS_AddRemoveMid_Payload_t erroneously contains a command header feild.

**Expected behavior**
Payloads should not contain headers.

**Reporter Info**
Dan Knutsen
NASA Goddard

**Comment by skliper** [comment]
https://github.com/nasa/DS/blob/2a6c6a2df5b2f00915a06f0a5ac30b9c327c725d/fsw/inc/ds_msg.h#L408-L413
