### ISSUE TITLE
DS: DS9007 Failure

### ISSUE THREAD

**Issue by skliper** [nasa/DS#18]
DS appears to have been updated and Descriptor text, pathname, basename and extention are no longer verified as specified in DS9007

Imported from GSFCCFS-1961

**Comment by dmknutsen** [comment]
Also worth note - is that the destination text reported always reports 'OK'...whether it is valid or not.

**Comment by skliper** [comment]
> Also worth note - is that the destination text reported always reports 'OK'...whether it is valid or not.

Documented in #25
