### ISSUE TITLE
Conditional compile macro uses wrong style of TRUE

### ISSUE THREAD

**Issue by gbaaseng** [nasa/DS#2]
In ds_file.c  the line reading
    #if (DS_MOVE_FILES == TRUE)
causes the subsequent section of code to always compile if TRUE is not defined, and if DS_MOVE_FILES is defined; and DS_MOVE_FILES is required to be defined by compiler directives in ds_verify.c. Throughout the rest of ds code, the lower-case C keyword 'true' is used, i.e '#if (DS_MOVE_FILES == true ).
When DS_MOVE_FILES is not set to 'true' in ds_platform_cfg.h, the build fails because 'Movename' does not get defined in ds_table.h, and the code section in ds_file.c needs it to be defined.

**Comment by skliper** [comment]
Similar to https://github.com/nasa/cFE/issues/1547.  Suggested path forward is to transition to ifdef to remove reliance on other headers.

**Comment by gbaaseng** [comment]
That would work, as a much larger change. There are quite a few cases where the logic may not be real amenable to just changing to ifdef, like "if (DS_FILE_HEADER_TYPE == DS_FILE_HEADER_CFE)" that may not convert easily to an ifdef. This particular case could quickly be resolved by just changing TRUE to true in this one instance (probably a missed change in a previous conversion from using TRUE to using true), and then the code will build correctly regardless of the setting of DS_MOVE_FILES in ds_platform_cfg.h. Note that ds does not appear to include stdbool.h anywhere, so I'm not quite sure that this is so closely related to cFE #1547. Or is this somewhat dependent on what compiler is used (I used gcc 4.8.x)?

**Comment by skliper** [comment]
Preprocessor logic change suggested is only for checks against true (or TRUE) since both have dependencies on those being defined to work correctly.  If stdbool.h isn't in the include path, evaluating against `true` will have the same issue as `TRUE`.  Note it may be getting pulled in from other includes since `true` is correctly used within the software (just want to avoid it's use in preprocessor conditionals since it can silently "error").

**Comment by gbaaseng** [comment]
OK, that sounds reasonable. One further thought then - the current ds_platform_cfg.h provides a default value for DS_MOVE_FILES in the ds source repo, with expectation that users modify in their target defs, with comments that describe its use. With this change the DS_MOVE_FILES would have to be deleted or commented out to not have it defined, rather than changing its value. The comment would have to explain this usage, and it could become unclear as users clear out commented-out code, and they lose the default example from their customized platform cfg. Generally platform_cfg files haven't depended on commenting out defined constants in this way, it seems to me.

**Comment by skliper** [comment]
You could `#undef` if a commented out `#define` is unacceptable (although may be less clear in the end and makes it such that you can't control the option from a higher level).  We don't force any pattern on the user in the end though, so they can keep or delete whatever comments they want.  We do have one example of using `#undef` at:
https://github.com/nasa/cFE/blob/a0c2de62934e61a93bb4282c0fc784cf4be50da9/cmake/sample_defs/cpu1_platform_cfg.h#L322-L332

**Comment by gbaaseng** [comment]
There's extensive precedent throughout ds and cfe generally to use the stdbool 'true'; a few precedents for using undef. No doubt numerous 'correct' ways to handle the matter. I'd have just gone with considering the original issue a typo or 'missed fix', rather than driving a bigger change, but up to you. Appreciate the discussion, I'll just watch the issue for your resolution. Thanks.

**Comment by skliper** [comment]
Updated in Caelum development cycle to no longer use `TRUE`, see 68cb97b489442cf2430b241f254811947d3731c8.  The #define/#undef vs false/true trade can be addressed as future work.
