### ISSUE TITLE
Unreachable branch in ds_file.c

### ISSUE THREAD

**Issue by chillfig** [nasa/DS#29]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
`OS_ObjectIdDefined(FileStatus->FileHandle)` always remains true following `DS_FileCreateDest(FileIndex);` The If statement logic about `DS_FileWriteData()` is not needed to maintain the same behavior.

**To Reproduce**
The missing coverage of fsw/src/ds_file.c can be seen in [Unit Test and Coverage](https://github.com/nasa/DS/actions/runs/2518546062).

**Expected behavior**
100% coverage

**Code snips**
https://github.com/nasa/DS/blob/df4432c60aee812c45ec9585d33e83ac01099574/fsw/src/ds_file.c#L276
https://github.com/nasa/DS/blob/df4432c60aee812c45ec9585d33e83ac01099574/fsw/src/ds_file.c#L321-L331

**System observed on:**
Continuous Integration

**Additional context**
None

**Reporter Info**
Justin Figueroa, ASRC Federal

**Comment by chillfig** [comment]
Was able to reach with 
`UT_SetHandlerFunction(UT_KEY(OS_OpenCreate), &UT_OS_write_SuccessHandler, NULL);`

https://github.com/chillfig/DS/blob/cd2bc9d1e8f18ef5c56c2d02002c78d49f74bb67/unit-test/ds_file_tests.c#L416

**Comment by skliper** [comment]
Looks to me like this should be linked to #34 and only closed once that merge is in.  @chillfig - could you link it and update your PR?
