### ISSUE TITLE
error: unknown type name 'CFE_SB_CmdHdr_t'

### ISSUE THREAD

**Issue by Somesort** [nasa/DS#3]
I want to believe that I am missing a step in the documentation somewhere, but when I bring DS into my apps folder, I update my MISSION_GLOBAL_APPLIST with DS and attempt to build and get this error amongst others.

/cFS/apps/DS/fsw/src/ds_msg.h:47:5: error: unknown type name ‘CFE_SB_CmdHdr_t’

Is there a script or tool that should be running that I am unaware of?

The training documentation here does not imply any other steps in Exercise 7 which is similar.
https://ntrs.nasa.gov/citations/20205000691

**Comment by skliper** [comment]
This is typically observed when using a version of cFE that is newer than what DS is compatible with.  Check the release information.

**Comment by Somesort** [comment]
Thanks, I believe you are right. I am trying to find a version of cFE that works with everything. It looks like the training and docs for cFE are also referencing repos that are not of the correct version.

**Comment by skliper** [comment]
Updates for Caelum cycle in 68cb97b489442cf2430b241f254811947d3731c8, Draco cycle update in 34d4f86ec1aa8a6c577c6040f3716e4cce235a33.  Should compile with both now.
