### ISSUE TITLE
Sends an event message on failure of registering with EVS

### ISSUE THREAD

**Issue by skliper** [nasa/DS#85]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
`CFE_EVS_SendEvent` is used when `CFE_EVS_Register` fails.  Should use `CFE_ES_WriteToSysLog` for a better chance of actually recording the error.

**Expected behavior**
Use a mechanism for reporting errors that's more likely to succeed in case of an EVS registration failure.

**Code snips**
https://github.com/nasa/DS/blob/04c01548a8eaaf5a1b4abb2b7d7548140e0cd6c0/fsw/src/ds_app.c#L197-L206

**System observed on:**
N/A

**Additional context**
Recommend checking the rest of the apps and marking as bug.

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
DS and FM have this issue.
The rest already use `CFE_ES_WriteToSysLog`.

**Comment by thnkslprpt** [comment]
Issue for FM: https://github.com/nasa/FM/issues/87
